use_frameworks!

target 'CalendarView_Example' do
  pod 'CalendarView', :path => '../'

  target 'CalendarView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
