platform :ios, '8.0'
use_frameworks!

target 'Colander_Example' do
  pod 'Colander', :path => '../'
  pod 'Reveal-SDK', :configurations => ['Debug']

  target 'Colander_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
